api/urls.py
from django.urls import path
from .views import Kamar_API

urlpatterns = [
    path('kamar/', Kamar_API, name='kamar'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500, handler403

urlpatterns = [
    path('', include('authentication.urls') ,name='home'),
    path('dashadmin/', include('dash_admin.urls')),
    path('dashtamu/', include('dash_tamu.urls')),
    path('api/', include('api.urls')),
    # path('admin/', admin.site.urls),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
handler404 = 'core.views.custom_page_not_found_view'
handler500 = 'core.views.custom_error_view'
handler403 = 'core.views.custom_permission_denied_view'

dash_tamu/urls.py
from django.urls import path, re_path

from dash_tamu import views

app_name = "dash_tamu"
urlpatterns = [
    path('', views.dashTamuView, name='dashtamu-home'),
    path('profil/', views.ProfilListView.as_view(), name='dashtamu-profil'),
    path('logpembayaran/', views.LogPembayaranTamuListView.as_view(), name='log-dash'),
    path('logpembayaran/pdf/', views.render_pdf_LogPembayaran_view, name='log-pdf'),

    #RegisterTamu
    path('register/profil', views.RegisterTamuView.as_view(), name='register-profil'),
    path('register/peraturan', views.PeraturanKostView.as_view(), name='register-peraturan'),
    path('register/paketkost', views.PaketKostView.as_view(), name='register-paketkost'),

    #daftarpaketkost
    path('tagihan/', views.PaketKostDashView.as_view(), name='paket'),
    #peraturanKost
    path('peraturan/', views.PeraturanView.as_view(), name='peraturan'),
    #Kritik
    path('kritik/', views.KritikSaranView.as_view(), name='kritik-saran'),

]

dash_tamu/models.py
from django.db import models

# Create your models here.
class ProfilTamuModel(models.Model):
    Nik             = models.CharField(max_length=16)
    Nama_lengkap    = models.CharField(max_length=50)
    No_tlp          = models.CharField(max_length=12)
    Email           = models.CharField(max_length=255)
    Tempat_lahir    = models.CharField(max_length=50)
    Tanggal_lahir   = models.DateField()
    Agama           = models.CharField(max_length=50)
    Pekerjaan       = models.CharField(max_length=50)
    Jenis_kelamin   = models.CharField(max_length=50)
    Alamat_asal     = models.CharField(max_length=255)
    Foto_ktp        = models.ImageField(upload_to='foto_ktp')
    published       = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}. {}".format(self.id, self.Nik)

class PaketKostModel(models.Model):
    Nik             = models.CharField(max_length=16)
    Paket           = models.CharField(max_length=50)
    
    def __str__(self):
        return "{}. {}".format(self.id, self.Nik)

class KritikSaranModel(models.Model):
    Nik             = models.CharField(max_length=16)
    Kritik          = models.CharField(max_length=250)
    Saran           = models.CharField(max_length=250)

    def __str__(self) :
        return "{}. {}".format(self.id, self.Nik)

        

dash_tamu/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.generic import FormView, TemplateView, ListView
from django.views.generic.edit import CreateView
from django.template import loader
from django.http import HttpResponse
from django.db import connection
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

#models
from .models import ProfilTamuModel, PaketKostModel
from dash_admin.models import KamarKostModel, PemasukanKostModel

#pdf
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa

#form
from .form import ProfilTamuForm,PaketKostForm,KritikSaranForm

#Dashboard View
@login_required(login_url="/")
def dashTamuView(request):
    Akun = request.user
    ProfilTamuModels = ProfilTamuModel.objects.filter(Nik=Akun)
    Statuskos = KamarKostModel.objects.raw('SELECT dash_admin_kamarkostmodel.*, dash_tamu_paketkostmodel.*,datediff(Waktu_out, current_date()) as selisih FROM dash_admin_kamarkostmodel INNER JOIN dash_tamu_paketkostmodel ON dash_admin_kamarkostmodel.Nik=dash_tamu_paketkostmodel.Nik WHERE dash_admin_kamarkostmodel.Nik=%s', [Akun])
    LogPembayaran = PemasukanKostModel.objects.filter(Nik=Akun)
    PaketKost = PaketKostModel.objects.filter(Nik=Akun)
    
    cursor = connection.cursor()
    cursor.execute('SELECT SUM(Jmlh_pemasukan) AS Total FROM dash_admin_pemasukankostmodel WHERE Nik=%s', [Akun])
    subtotal = cursor.fetchone()[0]
    if subtotal is None:
        subtotal = 0

    context = {
        'subtotal' : subtotal,
        'DataTamu' : ProfilTamuModels,
        'Statuskos' : Statuskos,
        'LogPembayaran' : LogPembayaran,
        'PaketKost' : PaketKost
    }
    context['segment'] = 'dashboard'
  
    if ProfilTamuModels.exists() :
        html_template = loader.get_template( 'dash_tamu/dashboard.html' )
        return HttpResponse(html_template.render(context, request))
    else:
        return redirect('/dashtamu/register/peraturan')

class LogPembayaranTamuListView(LoginRequiredMixin, ListView):
    model = PemasukanKostModel
    template_name = "dash_tamu/dashboard/logPembayaranTamu.html"
    context_object_name = 'obj'

    def get_queryset(self):
        Akun = self.request.user
        self.queryset = self.model.objects.raw('SELECT dash_admin_pemasukankostmodel.*, dash_tamu_profiltamumodel.Nama_lengkap  FROM dash_admin_pemasukankostmodel INNER JOIN dash_tamu_profiltamumodel ON dash_admin_pemasukankostmodel.Nik=dash_tamu_profiltamumodel.Nik WHERE dash_admin_pemasukankostmodel.Nik=%s', [Akun])
        return super().get_queryset()

def render_pdf_LogPembayaran_view(request):
    Akun = request.user
    obj = PemasukanKostModel.objects.raw('SELECT dash_admin_pemasukankostmodel.*, dash_tamu_profiltamumodel.Nama_lengkap  FROM dash_admin_pemasukankostmodel INNER JOIN dash_tamu_profiltamumodel ON dash_admin_pemasukankostmodel.Nik=dash_tamu_profiltamumodel.Nik WHERE dash_admin_pemasukankostmodel.Nik=%s', [Akun])
    template_path = 'dash_tamu/dashboard/printLogPembayaran.html'
    context = {'obj': obj}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

class ProfilListView(LoginRequiredMixin, ListView):
    model = ProfilTamuModel
    template_name = "dash_tamu/profil/profil.html"
    context_object_name = 'DataTamu'

    def get_queryset(self):
        Akun = self.request.user
        self.queryset = self.model.objects.filter(Nik=Akun)
        return super().get_queryset()

#Register Tamu
class PeraturanKostView(LoginRequiredMixin, TemplateView):
    template_name = 'dash_tamu/registerTamu/peraturan.html'

class RegisterTamuView(LoginRequiredMixin, CreateView):
    form_class = ProfilTamuForm
    template_name = "dash_tamu/registerTamu/regtamunew.html"
    success_url = '/dashtamu/register/paketkost'

class PaketKostView(LoginRequiredMixin, FormView):
    form_class = PaketKostForm
    template_name = 'dash_tamu/registerTamu/pilihanPaket.html'
    success_url = '/'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        else:
            return render(request, self.template_name, {'form': form })

#Peraturan Kost
class PeraturanView(LoginRequiredMixin, TemplateView):
    template_name ='dash_tamu/peraturankost/peraturankost.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['segment'] = 'PemasukanKost'
        return context

#harga list
class PaketKostDashView(LoginRequiredMixin, ListView):
    model = ProfilTamuModel
    template_name ='dash_tamu/Tagihan/tagihan.html'
    context_object_name = 'invoice'

    def get_queryset(self):
        Akun = self.request.user
        self.queryset = self.model.objects.raw('SELECT dash_tamu_profiltamumodel.*, dash_admin_kamarkostmodel.*, dash_tamu_paketkostmodel.*, CASE WHEN dash_tamu_paketkostmodel.Paket = 3 THEN dash_admin_kamarkostmodel.Waktu_out + INTERVAL 12 MONTH WHEN dash_tamu_paketkostmodel.Paket = 2 THEN dash_admin_kamarkostmodel.Waktu_out + INTERVAL 3 MONTH WHEN dash_tamu_paketkostmodel.Paket = 1 THEN dash_admin_kamarkostmodel.Waktu_out + INTERVAL 1 MONTH END AS Bulan_out, dash_admin_kamarkostmodel.Waktu_in + INTERVAL 1 MONTH AS Bulan_in, datediff(Waktu_out, current_date()) as selisih FROM dash_tamu_profiltamumodel INNER JOIN dash_admin_kamarkostmodel ON dash_tamu_profiltamumodel.Nik=dash_admin_kamarkostmodel.Nik INNER JOIN dash_tamu_paketkostmodel ON dash_admin_kamarkostmodel.Nik=dash_tamu_paketkostmodel.Nik WHERE dash_tamu_profiltamumodel.Nik =%s', [Akun])
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        Akun = self.request.user
        cursor = connection.cursor()
        cursor.execute('SELECT SUM(Jmlh_pemasukan) AS Total FROM dash_admin_pemasukankostmodel WHERE Nik=%s', [Akun])
        subtotal = cursor.fetchone()[0]
        if subtotal is None:
            subtotal = 0
        print(subtotal)
        context['segment'] = 'Tagihan'
        context['subtotal'] = subtotal
        return context

#Kritik & Saran
class KritikSaranView(LoginRequiredMixin, CreateView):
    form_class = KritikSaranForm
    template_name = 'dash_tamu/kritiksaran/kritikSaran.html'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['segment'] = 'KritikSaran'
        return context

dash_tamu/templates/dash_tamu/dashboard/logPembayaranTamu.html
{% extends "base/base-volt.html" %}

{% block title %} Dashboard - LogPembayaranDash {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
{% load humanize %}
<div class="col-12 col-xl-7 col-xxl-8 mb-4">
    <div class="row">
      <div class="col-12 mb-4">
        <div class="card border-0 shadow">
          <div class="card-header">
            <div class="row align-items-center">
              <div class="col">
              {% for obj in obj|slice:":1" %}
                <h2 class="fs-5 fw-bold mb-0">Log Pembayaran {{obj.Nama_lengkap|title}}</h2>
                {% endfor %}
              </div>
              <div class="col text-end"><a
                  href="{% url 'dash_tamu:log-pdf' %}"
                  class="btn btn-sm btn-primary"
                  target="_blank" 
                >Print</a></div>
            </div>
          </div>
          <div class="table-responsive">
            <table class="table align-items-center table-flush">
              <thead class="thead-light">
                <tr>
                  <th
                    class="border-bottom"
                    scope="col"
                  >No</th>
                  <th
                    class="border-bottom"
                    scope="col"
                  >NAMA</th>
                  <th
                    class="border-bottom"
                    scope="col"
                  >TGL_PEMBAYARAN</th>
                  <th
                    class="border-bottom"
                    scope="col"
                  >JMLH_DIBAYARAN</th>
                  <th
                    class="border-bottom"
                    scope="col"
                  >KETERANGAN</th>
                </tr>
              </thead>
              <tbody>
                {% for obj in obj %}
                <tr>
                  <th
                    class="text-gray-900"
                    scope="row"
                  >{{forloop.counter}}</th>
                  <td class="fw-bolder text-gray-500">{{obj.Nama_lengkap|title}}</td>
                  <td class="fw-bolder text-gray-500">{{obj.Tgl_pemasukan|date:"d F Y"}}</td>
                  <td class="fw-bolder text-gray-500">Rp. {{obj.Jmlh_pemasukan|intcomma}}</td>
                  <td class="fw-bolder text-gray-500">{{obj.Keterangan}}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}


<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

dash_tamu/templates/dash_tamu/dashboard/printLogPembayaran.html
<!DOCTYPE html>
<html lang="en">
{% load humanize %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LogPembayaran - {% for obj in obj %}{{obj.Nama_lengkap|title}}{% endfor %} | GatotkacaKost</title>

    <style>
        th, td{
            padding: 5px;
        }
        table.center {
            margin-left: auto;
            margin-right: auto;
        }

    </style>
</head>
<body>
    
    <table border: 1px>
    <tr>
    <td>
    <div><img width='100px' src="{% static 'assets_pdf/Gartnew.png' %}"></div>
    </td>
    <td style="text-align: right;"><h1>Gatotkaca Kost<br>Sleman, Yogyakarta<br>Gatotkacanetwork@gmail.com</h1></td>
    </tr>
    </table>
    <hr>

    <br>
    <h1>Log Pembayaran {% for obj in obj|slice:":1" %}{{obj.Nama_lengkap|title}}{% endfor %}</h1>
    <table style="border: 1px solid black;border-collapse: collapse;" >
    <thead>
    <tr>
    <th>No</th>
    <th>Nama</th>
    <th>TGL_PEMBAYARAN</th>
    <th>JMLH_DIBAYARAN</th>
    <th>KETERANGAN</th>
    </tr>
    </thead>
    <tbody>
    {% for obj in obj %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{obj.Nama_lengkap|title}}</td>
            <td>{{obj.Tgl_pemasukan|date:"d F Y"}}</td>
            <td>{{obj.Jmlh_pemasukan|intcomma}}</td>
            <td>{{obj.Keterangan}}</td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
</body>
</html>