api/urls.py
from django.urls import path
from .views import Kamar_API

urlpatterns = [
    path('kamar/', Kamar_API, name='kamar'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500, handler403

urlpatterns = [
    path('', include('authentication.urls') ,name='home'),
    path('dashadmin/', include('dash_admin.urls')),
    path('dashtamu/', include('dash_tamu.urls')),
    path('api/', include('api.urls')),
    # path('admin/', admin.site.urls),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
handler404 = 'core.views.custom_page_not_found_view'
handler500 = 'core.views.custom_error_view'
handler403 = 'core.views.custom_permission_denied_view'

dash_admin/urls.py
from django.urls import path
from dash_admin import views
from .views import (KomfirmasiTamuBaruView,
                    ProfilTamuListView,
                    ProfilTamuUpdateView,
                    ProfilTamuDetailView,
                    ProfilTamuDeleteView,
                    KamarTamuUpdateView,
                    KamarTamuDeleteView,
                    KonfimasuTamyViewNew,
                    kritikSaranListView,
                    KritikSaranDeleteView,
                    LogPembayaranListView,
                    PendapatanListView,
                    LogPembayaranDeleteView,
                    LogPembayaranDashListView,
                    send_gmail,
                    render_pdf_view,
                    PembayaranTamuBaruNew,
                    LogPembayaranUpdateView,
                    renderPdfLogPembayaran,
                    pengeluaranDeleteView,
                    UpdatePaketView,
                    kamarTamuView)

app_name = 'dashadmin'
urlpatterns = [

    # The home page
    path('', views.index, name='dashadmin-home'),
    path('logpembayaran/', LogPembayaranDashListView.as_view(), name='log-dash'),
    path('logpembayaran/pdf/', renderPdfLogPembayaran, name='log-pdf'),

    # pembayaran
    path('pembayaran/tamubaru', PembayaranTamuBaruNew, name='tambah-tamu-baru'),
    path('pembayaran/', KonfimasuTamyViewNew, name='tambah-pembayaran'),

    #Data>>Profil Tamu
    path('data/profil/', ProfilTamuListView.as_view(), name='profiltamu-view'),
    path('data/profil/update/<int:pk>', ProfilTamuUpdateView.as_view(), name='profiltamu-update'),
    path('data/profil/detail/<int:pk>', ProfilTamuDetailView.as_view(), name='profiltamu-detail'),
    path('data/profil/delete/<int:pk>', ProfilTamuDeleteView.as_view(), name='profiltamu-delete'),

    #Data>>Kamar Tamu
    path('data/kamar/', kamarTamuView.as_view(), name='kamartamu-view'),
    path('data/kamar/kamarbaru/', KomfirmasiTamuBaruView.as_view(), name='kamartamu-create'),
    path('data/kamar/update/<int:pk>', KamarTamuUpdateView.as_view(), name='kamartamu-update'),
    path('data/kamar/updatepaket/<int:pk>', UpdatePaketView.as_view(), name='kamartamu-update-paket'),
    path('data/kamar/delete/<int:pk>', KamarTamuDeleteView.as_view(), name='kamartamu-delete'),

    #Keuangan >> Pemasukan
    path('keuangan/pemasukan/', PendapatanListView, name='pemasukan-view'),
    path('keuangan/pemasukan/delete/<int:pk>', pengeluaranDeleteView.as_view(), name='pengeluaran-delete'),

    #Keuangan >> Log Pembayaran
    path('keuangan/logpembayaran/', LogPembayaranListView, name='LogPembayaran-view'),
    path('keuangan/logpembayaran/update/<int:pk>', LogPembayaranUpdateView.as_view(), name='LogPembayaran-update'),
    path('keuangan/logpembayaran/delete/<int:pk>', LogPembayaranDeleteView.as_view(), name='LogPembayaran-delete'),

    #KritikSaran
    path('kritik/', kritikSaranListView.as_view(), name='kritikSaran-view'),
    path('kritik/delete/<int:pk>', KritikSaranDeleteView.as_view(), name='kritikSaran-delete'),

    #Tagihan
    path('email/<str:Email>', send_gmail, name='send_mail'),
    path('pdf/<str:Nik>', render_pdf_view, name='pdf-tagihan')
]

dash_admin/forms.py
from decimal import Clamped
from django import forms
from .models import KamarKostModel,PemasukanKostModel,PengeluaranKostModel

class KamarKostForm(forms.ModelForm):
    
    class Meta :
        model = KamarKostModel
        fields = [
            'Nik',
            'No_kamar',
            'Waktu_in',
            'Waktu_out'
        ]

        widgets = {
            'Nik' : forms.NumberInput(
                attrs ={
                    'id' : 'state',
                    'class' : 'form-control w-100',
                    'placeholder' : 'Masukan NIK KTP',
                }
            ),
            'No_kamar' : forms.NumberInput(
                attrs ={
                    'class' : 'form-control',
                    'placeholder' : 'Masukan No_kamar',
                }
            ),
            'Waktu_in' : forms.DateInput(
                attrs ={
                    'class' : 'form-control',
                    'type'  : 'date',
                }
            ),
            'Waktu_out' : forms.DateInput(
                attrs ={
                    'class' : 'form-control',
                    'type'  : 'date',
                }
            ),
        }
    
class PemasukanKostForm(forms.ModelForm):
    class Meta :
        model = PemasukanKostModel
        fields = [
            'Nik',
            'Tgl_pemasukan',
            'Jmlh_pemasukan',
            'Keterangan'
        ]

        widgets = {
            'Nik' : forms.TextInput(
                attrs ={
                    'class' : 'form-control',
                    'placeholder' : 'Masukan NIK KTP',
                    
                }
            ),
            'Tgl_pemasukan' : forms.DateInput(
                attrs ={
                    'id' : 'birthday',
                    'class' : 'form-control',
                    'type'  : 'date',
                }
            ),
            'Jmlh_pemasukan' : forms.NumberInput(
                attrs ={
                    'class' : 'form-control',
                    'placeholder' : 'Masukan Jmlh_pemasukan',
                }
            ),
            'Keterangan' : forms.TextInput(
                attrs ={
                    'class' : 'form-control',
                    'placeholder' : 'Keterangan',
                }
            ),
        }

class PengeluaranKostForm(forms.ModelForm):
    class Meta :
        model = PengeluaranKostModel
        fields = [
            'Pengeluaran',
            'Tgl_pengeluaran',
            'jmlh_pengeluaran'
        ]

        widgets = {
            'Pengeluaran' : forms.TextInput(
                attrs ={
                    'class' : 'form-control',
                    'placeholder' : 'Masukan Pengeluaran',
                    
                }
            ),
            'Tgl_pengeluaran' : forms.DateInput(
                attrs ={
                    'class' : 'form-control',
                    'type'  : 'date',
                }
            ),
            'jmlh_pengeluaran' : forms.NumberInput(
                attrs ={
                    'class' : 'form-control',
                    'placeholder' : 'Masukan jmlh_pengeluaran',
                }
            ),
        }

dash_admin/views.py
from django import template
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
import datetime
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

#mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags

#pdf
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa

#form
from .forms import KamarKostForm, PemasukanKostForm, PengeluaranKostForm
from dash_tamu.form import ProfilTamuForm, PaketKostForm

#models
from .models import KamarKostModel,PemasukanKostModel, PengeluaranKostModel
from dash_tamu.models import ProfilTamuModel,PaketKostModel, KritikSaranModel
from django.db import connection

@login_required(login_url="/")
@permission_required('user.is_staff')
def index(request):
    context = {}

    TimeNow = datetime.datetime.now().strftime('%Y')
    context['TimeNow'] = TimeNow

    #Pendapatan Tahun Sekarang
    cursor = connection.cursor()
    cursor.execute('SELECT SUM(Jmlh_pemasukan) AS Total FROM dash_admin_pemasukankostmodel WHERE YEAR(Tgl_pemasukan)= YEAR(NOW())')
    PendapatanTahunIni = cursor.fetchone()[0]
    if PendapatanTahunIni is None:
        PendapatanTahunIni = 0
    context['PendapatanTahunIni'] = PendapatanTahunIni

    #Pendapatan Chart
    data = []
    count = 0
    while (count < 13):
        cursor = connection.cursor()
        cursor.execute("select SUM(Jmlh_pemasukan) AS Total from dash_admin_pemasukankostmodel where month(Tgl_pemasukan)=%s and year(Tgl_pemasukan) =%s", [count, TimeNow])
        bulan_1 = cursor.fetchone()[0]
        if bulan_1 == None:
            bulan_1 = 0
        float_str = float(bulan_1)
        bulan_1 = int(float_str)
        data.append(bulan_1)
        count = count + 1

    data.pop(0)
    context['data_Main_chart'] = data

    #Pendapatan Tahunan Card 2
    Pendapatan = []
    x = 1
    while (x < 6):
        cursor = connection.cursor()
        cursor.execute('SELECT SUM(Jmlh_pemasukan) AS Total FROM dash_admin_pemasukankostmodel WHERE YEAR(Tgl_pemasukan)=202%s', [x])
        Pendapatantahuan = cursor.fetchone()[0]
        if Pendapatantahuan == None:
            Pendapatantahuan = 0
        Pendapatantahuan = int(Pendapatantahuan)
        Pendapatan.append(Pendapatantahuan)
        x = x + 1

    context['Pendapatan_pertahun'] = Pendapatan


    #gender Chart
    gender = []

    cursor = connection.cursor()
    cursor.execute('SELECT COUNT(Jenis_kelamin) FROM `dash_tamu_profiltamumodel` WHERE Jenis_kelamin="pria"')
    pria = cursor.fetchone()[0]

    cursor = connection.cursor()
    cursor.execute('SELECT COUNT(Jenis_kelamin) FROM `dash_tamu_profiltamumodel` WHERE Jenis_kelamin="wanita"')
    wanita = cursor.fetchone()[0]

    gender.append(pria)
    gender.append(wanita)
    context['gender'] = gender

    context['segment'] = 'index'
    context['JumalahTamu'] = ProfilTamuModel.objects.all().count()

    #tamu daftar chart
    tamu = []
    count = 0
    while (count < 13):
        cursor = connection.cursor()
        cursor.execute('SELECT COUNT(*) FROM dash_tamu_profiltamumodel where month(published)=%s and year(published) =%s', [count, TimeNow])
        tamu_1 = cursor.fetchone()[0]
        if tamu_1 == None:
            tamu_1 = 0

        tamu.append(tamu_1)
        count = count + 1

    tamu.pop(0)
    context['data_tamu_chart'] = tamu

    #card Jumlah Tamu
    cursor = connection.cursor()
    cursor.execute('SELECT COUNT(*) FROM dash_admin_kamarkostmodel WHERE Waktu_out >= current_date()')
    TamuAktif = cursor.fetchone()[0]
    context['TamuAktif'] = TamuAktif

    #Card Pendapatan Bulan Ini
    cursor = connection.cursor()
    cursor.execute("SELECT SUM(Jmlh_pemasukan) AS Total FROM dash_admin_pemasukankostmodel WHERE CONCAT(YEAR(Tgl_pemasukan),'/',MONTH(Tgl_pemasukan))=CONCAT(YEAR(NOW()),'/',MONTH(NOW()))")
    totalBulan = cursor.fetchone()[0]
    if totalBulan is None:
        totalBulan = 0
    context['totalBulan'] = totalBulan

    #Card Log Pembayaran Bulan Ini
    context['LogPembayaran'] = PemasukanKostModel.objects.raw("SELECT dash_admin_pemasukankostmodel.*, dash_tamu_profiltamumodel.Nama_lengkap FROM dash_admin_pemasukankostmodel INNER JOIN dash_tamu_profiltamumodel on dash_tamu_profiltamumodel.Nik = dash_admin_pemasukankostmodel.Nik WHERE CONCAT(YEAR(Tgl_pemasukan),'/',MONTH(Tgl_pemasukan))=CONCAT(YEAR(NOW()),'/',MONTH(NOW()))")
    
    #Card Keuntungan Bersih Tahun Ini
    cursor = connection.cursor()
    cursor.execute('SELECT SUM(jmlh_pengeluaran) AS Total FROM dash_admin_pengeluarankostmodel WHERE YEAR(Tgl_pengeluaran)= YEAR(NOW())')
    PengeluaranTahunIni = cursor.fetchone()[0]
    if PengeluaranTahunIni is None:
        PengeluaranTahunIni = 0
    context['PengeluaranTahunIni'] = PengeluaranTahunIni
    TotalBersih = PendapatanTahunIni - PengeluaranTahunIni
    context['TotalBersih'] = TotalBersih

    html_template = loader.get_template( 'dash_admin/dashboard.html' )
    return HttpResponse(html_template.render(context, request))

class LogPembayaranDashListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = 'user.is_staff'
    model = PemasukanKostModel
    template_name = "dash_admin/dashboard/logPembayaranDash.html"
    context_object_name = 'obj'

    def get_queryset(self):
        self.queryset = self.model.objects.raw("SELECT dash_admin_pemasukankostmodel.*, dash_tamu_profiltamumodel.Nama_lengkap FROM dash_admin_pemasukankostmodel INNER JOIN dash_tamu_profiltamumodel on dash_tamu_profiltamumodel.Nik=dash_admin_pemasukankostmodel.Nik WHERE YEAR(Tgl_pemasukan)= YEAR(NOW()) ORDER BY `dash_admin_pemasukankostmodel`.`Tgl_pemasukan` DESC")
        return super().get_queryset()

@login_required(login_url="/")
@permission_required('user.is_staff')
def renderPdfLogPembayaran(request):
    obj = PemasukanKostModel.objects.raw("SELECT dash_admin_pemasukankostmodel.*, dash_tamu_profiltamumodel.Nama_lengkap FROM dash_admin_pemasukankostmodel INNER JOIN dash_tamu_profiltamumodel on dash_tamu_profiltamumodel.Nik=dash_admin_pemasukankostmodel.Nik WHERE YEAR(Tgl_pemasukan)= YEAR(NOW()) ORDER BY `dash_admin_pemasukankostmodel`.`Tgl_pemasukan` DESC")
    template_path = 'dash_admin/dashboard/pdfLogPembayaranDash.html'
    TimeNow = datetime.datetime.now().strftime('%Y')
    context = {'myvar': 'this is your template context', 'obj' : obj, 'TimeNow' : TimeNow}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

#Pembayaran
@login_required(login_url="/")
@permission_required('user.is_staff')
def KonfimasuTamyViewNew(request):
    template_name = None
    context = None

    if request.user.is_authenticated:
        form = PemasukanKostForm()
        profilTamu = ProfilTamuModel.objects.all()

        context = {
            'form' : form,
            'profilTamu' : profilTamu
        }

        context['segment'] = 'Pembayaran'

        Tagihan = None
        if request.method == 'POST':
            if 'NAMA' in request.POST:
                Tagihan = request.POST['NAMA']
                context['Tagihan'] = Tagihan
                context['invoice'] = ProfilTamuModel.objects.raw('SELECT dash_tamu_profiltamumodel.*, dash_admin_kamarkostmodel.*,dash_admin_kamarkostmodel.Waktu_out + INTERVAL 1 MONTH AS Bulan_out,dash_admin_kamarkostmodel.Waktu_in + INTERVAL 1 MONTH AS Bulan_in , current_date() as tgl_sekarang, datediff(Waktu_out, current_date()) as selisih FROM dash_tamu_profiltamumodel INNER JOIN dash_admin_kamarkostmodel ON dash_tamu_profiltamumodel.Nik=dash_admin_kamarkostmodel.Nik WHERE dash_tamu_profiltamumodel.Nik =%s', [Tagihan])
                context['PaketKost'] = PaketKostModel.objects.filter(Nik=Tagihan)
            else:
                Tagihan = False

        form = PemasukanKostForm(request.POST)
        if form.is_valid():
            rescuee_instance  = form.save()
            idProfil = ProfilTamuModel.objects.filter(Nik=rescuee_instance.Nik)
            for idProfil in idProfil:
                a = idProfil.id
            return redirect('dashadmin:kamartamu-update', a)
        else:
            form = PemasukanKostForm()
        template_name = 'dash_admin/konfirmasi/perpanjangTamu.html'
    else:
        template_name = 'auth/login.html'
    
    return render(request, template_name, context)

@login_required(login_url="/")
@permission_required('user.is_staff')
def PembayaranTamuBaruNew(request):
    template_name = None
    context = None
    
    if request.user.is_authenticated:
        form = PemasukanKostForm()
        profilTamu = ProfilTamuModel.objects.all()

        context = {
            'form' : form,
            'profilTamu' : profilTamu,
            'segment' : 'Pembayaran'
        }

        Tagihan = None
        if request.method == 'POST':
            if 'NAMA' in request.POST:
                Tagihan = request.POST['NAMA']
                context['Tagihan'] = Tagihan

dash_admin/templates/dash_admin/keuangan/logPembayaranUpdate.html
{% extends "base/base-volt.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
  <div class="d-block mb-4 mb-md-0">
    <nav
      aria-label="breadcrumb"
      class="d-none d-md-inline-block"
    >
      <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
        <li class="breadcrumb-item">
          <a href="/">
            <svg
              class="icon icon-xxs"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
              ></path>
            </svg>
          </a>
        </li>
        <li class="breadcrumb-item"><a href="/dashadmin/pembayaran/">Pembayaran</a></li>
        <li class="breadcrumb-item"><a href="/dashadmin/kamar/">Input kamar</a></li>
      </ol>
    </nav>
    <h2 class="h4">Update Profil Tamu</h2>
    <p class="mb-0">Your web analytics dashboard template.</p>
  </div>
</div>

<div class="card card-body shadow border-0 table-wrapper table-responsive">
  <form
    method='POST'
  >
    {% csrf_token %}
    {{ form.as_table }}
    
    <br><br>
    <button
      class='btn btn-primary'
      type='submit'
    >Submit</button>
  </form>
</div>
{% endblock content %}


<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

dash_admin/templates/dash_admin/keuangan/logPembayaranView.html
{% extends "base/base-volt.html" %}
{% load humanize %}

{% block title %} Keuangan - LogPembayaran {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
        <div class="d-block mb-4 mb-md-0">
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
                <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                    <li class="breadcrumb-item">
                        <a href="#">
                            <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="#">Keuangan</a></li>
                    <li class="breadcrumb-item active" aria-current="page">log Pembayaran</li>
                </ol>
            </nav>
            <h2 class="h4">Log Pembayaran</h2>
        </div>
    </div>

<div class="row">
  <div class="col-lg-12 col-md-12">
    <div class="card ">
      <div class="card-header">
        <h4 class="card-title"> Log Pembayaran</h4>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="state" class="my-1 mr-2">Nama Pembayar: </label>
              <select
                class='form-control'
                name="NAMA"
                id="state"
                class="w-100"
                onChange="form.submit();"
              >
                <option>----- Pilih Nama -----</option>
                {% for profilTamu in profilTamu %}
                <option value={{profilTamu.Nik}}>{{profilTamu.Nama_lengkap|title}}</option>
                {% endfor %}
              </select>
          </div>
        </form>
        <h5 class="card-title">TOTAL PEMASUKAN : Rp. {{subtotal|intcomma}}</h5>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table tablesorter " id="">
            <thead class=" text-primary">
              <tr>
                <th>
                  Nama
                </th>
                <th>
                  tgl_pembayaran
                </th>
                <th>
                  jmlh_dibayaran
                </th>
                <th>
                  keterangan
                </th>
                <th>
                  action
                </th>
              </tr>
            </thead>
            <tbody>
              {% for invoice in invoice %}
              <tr>
                <td>
                  <h6>{{invoice.Nama_lengkap|title}}</h6>
                </td>
                <td>
                  {{invoice.Tgl_pemasukan}}
                </td>
                <td>
                  Rp. {{invoice.Jmlh_pemasukan|intcomma}}
                </td>

                <td>
                  {{invoice.Keterangan}}
                </td>
                <td>
                  <a class="btn btn-warning" href="{% url 'dashadmin:LogPembayaran-update' invoice.pk %}">Edit</a>
                  <a class="btn btn-danger" href="{% url 'dashadmin:LogPembayaran-delete' invoice.pk %}">Delete</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  {% endblock content %}

  <!-- Specific Page JS goes HERE  -->
  {% block javascripts %}
  {% endblock javascripts %}